
- name: Check existence of matrix-matrix-strauby-bot service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-bot-matrix-strauby-bot.service"
  register: matrix_bot_matrix_reminder_bot_service_stat

- when: matrix_bot_matrix_reminder_bot_service_stat.stat.exists | bool
  block:
    - name: Ensure matrix-matrix-strauby-bot is stopped
      ansible.builtin.service:
        name: matrix-bot-matrix-strauby-bot
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure matrix-bot-matrix-strauby-bot.service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/matrix-bot-matrix-strauby-bot.service"
        state: absent

    - name: Ensure Matrix matrix-strauby-bot paths don't exist
      ansible.builtin.file:
        path: "{{ matrix_bot_matrix_reminder_bot_base_path }}"
        state: absent
